### ISSUE TITLE
Lack of documentation on meta data support

### ISSUE THREAD

**Issue by GazbonicAcid** [cyanobacterium/AdditionalLootTables#1]
The only way to find out about the meta data support is to go through the example loot tables.
However I had mods that add ALT loot tables in the pack that I own before I had ALT in it.
I am adding ALT to it because of this.
It would seem that because of the other mods' loot tables ALT did not generate the examples.
The Forge page, zero info on it.
The wiki, zero info on it.
In-game command to generate examples, does not exist.
The only place I found info on the meta data support is the example loot table generator class in the github source.

**Comment by DrPlantabyte** [comment]
Thank you for bringing this to my attention. I actually don't know much about loot tables myself as of yet. I just knew that I needed to shuffle new content into the default loot tables used by Minecraft.

The best documentation I can find at the moment is http://minecraft.gamepedia.com/Loot_table but that's not even as useful as simply looking inside the assets folder of your Minecraft install.

**Comment by GazbonicAcid** [comment]
I was talking about the documentation of **_you're mod's_** features.
The only place I could find anything on **_you're mod's_** meta data support was the examples config generator class in the source.

**Comment by DrPlantabyte** [comment]
I understand your frustration, but I don't know how my mod does it either. I just forward the json files into Minecraft, so everything that applies to loot tables in vanilla resourcepacks applies here as well, and I honestly wish I knew how loot tables work. I just copy-pasted some stuff into the example class and modified it.

In short, I made a mod I don't understand, so I haven't documented it yet.

However, I agree with you that I **SHOULD** have decent documentation beyond a cryptic example. What is your preferred type of documentation? Wiki article? Read-me file? In-game manual? Stand-alone config file generator program? Hands-on tutorial? (I don't have the expertise to make a video, unfortunately)

**Comment by GazbonicAcid** [comment]
With this mod, I have to say all 3.
Wiki article online,
put it in a/the read-me file on git hub,
and an in-game manual with either the read-me file or wiki article from before.

**Comment by DrPlantabyte** [comment]
I only have time for one, so I'll work on the Wiki article since you listed that first.

**Comment by GazbonicAcid** [comment]
I found this gamepedia wiki page.
http://minecraft.gamepedia.com/Loot_table

**Comment by DrPlantabyte** [comment]
Yeah, that's not useful enough to meet your demands, though. I found a more thorough (but slightly out of date) description at http://www.minecraftforum.net/forums/minecraft-discussion/redstone-discussion-and/command-blocks/2546347-1-9-custom-loot-tables

There just isn't much in the way of any documentation for loot tables in MC 1.9 out there as yet

EDIT: I added more details to the wiki page: http://drcyano.wikidot.com/wiki:additional-loot-tables
Is that more to your liking? What questions do you still have so I can put the answers there (after learning the answer for myself).

**Comment by GazbonicAcid** [comment]
Awesome, thanks! :)
