### ISSUE TITLE
Critical Mod Compatibility Issue: WorldEdit

### ISSUE THREAD

**Issue by brisingraerowing** [cyanobacterium/AdditionalLootTables#4]
The latest version of this mod prevents World Edit from working. Confirmed with various combinations of mods, only removing this one allowed WorldEdit to work.

This only happens when a mod that uses this one (e.g. Base Metals) is installed as well.

As I use WE extensively, this is a deal breaker for me.

I believe that the reflection hack you use has something to do with the issue.

**Comment by jriwanek** [comment]
On the mention of that, with the new loot table system in forge, the reflection hack probably isn't necessary any more.

**Comment by DrPlantabyte** [comment]
Try v1.03p1 (or v1.05 for MC 1.9.4) and see if that fixes it.

**Comment by brisingraerowing** [comment]
I can confirm that WorldEdit now works. Thanks.

OT: I HATE it when a crash doesn't give enough information to figure out what caused it. I am trying to debug a creative mode crash when MC fails to render a dandelion on a creative tab with the exception "Already Building" and no mods listed in the stack trace. :angry:
