### ISSUE TITLE
mob drops

### ISSUE THREAD

**Issue by m1jordanallen** [cyanobacterium/AdditionalLootTables#5]
Hello, I have been looking for a mod that would help me get custom loot tables into a pack so it isnt world dependent.  This mod looks perfect for that.  I am unable to get entities file to be pulling properly though.  When I put the json into its proper place in the world folder it works great, but through the mod it doesn't.  I am trying to replace the zombie.json file in the entity folder.  I placed these into a folder to follow the proper format.  I use a few of your other mods and followed their folder format and I read the documentation.   I am hoping to replace the loot table as I am not using it to add modded items, but to edit vanilla items on vanilla mob drops.  

I have not seen this mod used in this fashion, but it appears that it should work according to the documentation, but I may be misunderstanding.

**Comment by jriwanek** [comment]
I'll have a look into it and let you know, a sample of the configs you're using would help greatly.

**Comment by m1jordanallen** [comment]
I will post a copy of the loot table when I get home from work.  I used the loot table in the minecraft assets and copied a drop to include a second possibility. Me and a buddy ended up making a mod that would do what we need, but this feature may be useful for others.  To my knowledge there isnt a mod allowing vanilla loot tables to be loaded outside the world folder except this at the moment.  No rush on my part though :)

**Comment by DrPlantabyte** [comment]
Sorry for the long delay in responding. I don't have time for modding anymore :(
Anyway, ALT adds to the loot tables but does not replace the existing ones.

**Comment by jriwanek** [comment]
Should now work correctly in 2.0.1
