### ISSUE TITLE
[1.9.4] Enabling this mod makes my JEI interface disappear

### ISSUE THREAD

**Issue by Dragnier** [cyanobacterium/AdditionalLootTables#6]
The second this mod is enabled in my 1.9.4 personal modpak, JEI overlay completely disappears and cannot be accessed in any way. 

This is probably due to some change in an update on the JEI end, because I've used your mod with it before and had no issues. 

It took me a couple of hours to figure out it was your mod because I did not expect such an issue to be caused by your mod since it doesn't deal with UI properties or anything. This happens with just JEI and your mod loaded with the most recent 1.9.4 forge version installed.

**Comment by jriwanek** [comment]
What other mods are you using, Also, versions of JEI, ALT & Forge ("Most Recent" isn't descriptive) please. (I'll attempt to look into it, but I want to set up identically)

**Comment by jriwanek** [comment]
A quick check with ALT 1.9.4-1.05, Base Metals 1.9.4-2.3.2.6, Orespawn 1.9.4-1.0.3, and JEI 1.9.4-3.6.8.225 turns up no issues, so it could possibly be related to ALT, but it's likely cross-mod and not with JEI/ALT if so. Definitely gonna need a list of mods and versions to diagnose.

**Comment by Dragnier** [comment]
You are probably correct that it was something cross-mod; as I have since edited the modpack (including updating other mods as they released new versions) and it no longer has this issue. I am going to guess that one of those updates fixed the issue. If it crops back up, I'll post more info about it here. Until then, this should probably be closed.
